env:
    MANIFEST: git://github.com/SHRP/manifest.git
    MANIFEST_BRANCH: v3_11.0
    DEVICE: lisa
    DT_LINK: https://github.com/Aswinbuilds/android_device_xiaomi_lisa
    DT_PATH: device/xiaomi/lisa
    TARGET: bootimage
    BOTTOKEN: ${{ secrets.bottoken }}

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
  
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - sudo apt install curl -y
       - sudo apt-get install git -y
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt upgrade -y 
       - git config --global user.name "aswin11234"
       - git config --global user.email "aswinsanker08@gmail.com"
       - ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
  
  Sync_script:
       - sudo apt-get install tmate -y
       - tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a headless mode
       - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string
       - sleep 100

  Build_script:
       - curl https://raw.githubusercontent.com/Sushrut1101/Ubuntu-Tmate/master/spam.sh > ~/spam.sh
       - bash ~/spam.sh
